### ISSUE TITLE
AutoObject fails for nested folder

### ISSUE THREAD

**Issue by TravisThomp** [kitschpatrol/svelte-tweakpane-ui#10]
When using an object such as 

```
const object = {
    aFolder: {
        aSetting: 0,
        bFolder: {
            bSetting: 0,
            cFolder: {
                cSetting: 0,
            },
        },
    },
}
```

The Panel will only display the slider for the `A` setting and then show an empty `B` folder

![image](https://github.com/kitschpatrol/svelte-tweakpane-ui/assets/50000930/019b547c-c429-42f1-ba79-93cd5f768496)

**Comment by TravisThomp** [comment]
Seems like my svelte was just bugging... Works now :D

**Comment by kitschpatrol** [comment]
Ok great, it's working ok on my end. (Assuming `let` instead of `const`.)

![Screenshot 2024-06-02 at 10 58 17 of Chromium - httplocalhost5174TestAutoObjectNesting svelte@2x](https://github.com/kitschpatrol/svelte-tweakpane-ui/assets/194164/4014bcd3-4613-4926-9c5f-622e888adbeb)

In development builds, I've found that sometimes HMR can start to get weird, and a hard refresh takes care of it.

Feel free to reopen if you run into this again.
