### ISSUE TITLE
Changing font size

### ISSUE THREAD

**Issue by cristianvogel** [kitschpatrol/svelte-tweakpane-ui#11]
Hi, 

my users are requesting larger fonts on the value readouts, I can't seem to change the size using the theme  ` baseFontFamily: "sans-serif",` setting. Should I be able to pass a font-size attribute somehow?

**Comment by kitschpatrol** [comment]
Svelte Tweakpane UI's [theming system](https://kitschpatrol.com/svelte-tweakpane-ui/docs/themes) exposes the same variables that are used in [Tweakpane's underlying theme customization implementation](https://tweakpane.github.io/docs/theming/), which does not include `font-size`. There's a way to directly override the CSS in Tweakpane, [discussed here](https://github.com/cocopon/tweakpane/issues/395), but I'm not sure how far it can be pushed before layouts start to break.

As an alternative, Svelte Tweakpane UI adds the [`scale` prop on the `<Pane>` component](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/pane#scale), which makes it easy to increase the size of the entire pane using CSS transforms, and it looks great since Tweakpane is all vectors.

Also, I've also noticed that especially on Windows, the default monospace typeface looks very anemic and can be hard to read, swapping in a slightly heavier font can improve legibility even at the same size.

**Comment by cristianvogel** [comment]
ok, thanks!
