### ISSUE TITLE
Large number of dependencies

### ISSUE THREAD

**Issue by stefnotch** [kitschpatrol/svelte-tweakpane-ui#2]
I installed this, and npm said `added 57 packages, and audited 188 packages in 16s`
Adding 57 packages seems like a lot to me.

I took a short peek at the package.json, and noticed the `bumpp` dependency. Could this dependency potentially be turned into a dev dependency?
https://github.com/kitschpatrol/svelte-tweakpane-ui/blob/a0e9d75642ea960302c5a92aad5219ba5c8afea4/package.json#L228C5-L228C11

**Comment by kitschpatrol** [comment]
Thanks for opening this — and oops yes thank you, I will move `bumpp` to dev dependencies in the next release, that was a mistake.

In general, a design priority for the library is a "batteries included" approach for ease of development — bundling Tweakpane plugins, in particular, comes at the expense of some extra dependencies during development. My sense is that they're not a burden to the end-user since they can be tree-shaken away in the production build. 

The only other non-essential direct dependencies that I can see are  `esm-env`, and  `nanoid`... both of which are pretty light and have zero dependencies of their own.

(Also, I'd definitely recommend against adding up the dev dependencies. 🫣😅.)

**Comment by stefnotch** [comment]
Awesome, that sounds perfect then.

**Comment by kitschpatrol** [comment]
Fixed has been released in version 1.1.0.

**Comment by stefnotch** [comment]
Thank you so much for this super fast improvement. 

Time to continue absolutely enjoying this little library.

**Comment by kitschpatrol** [comment]
I'm going to track work on reducing the final bundle size in issue #6.
