### ISSUE TITLE
Logarithmic scale for generic input

### ISSUE THREAD

**Issue by ecstrema** [kitschpatrol/svelte-tweakpane-ui#5]
Hey! Awesome library! 

I was looking into how to use a logarithmic scale for a slider, and realized it was more involved than listening to on:change and updating the value accordingly.

Do you have any pointers on how to do it?

**Comment by kitschpatrol** [comment]
Hey thanks and good question!

There's some discussion of this in the Tweakpane repo [here](https://github.com/cocopon/tweakpane/issues/56) and [here](https://github.com/cocopon/tweakpane/issues/438)... the author suggests writing a Tweakpane plugin to do this "properly".

I'd be happy to add a Tweakpane Plugin that accomplishes this to the Svelte TweakpaneUI library, but I don't think anyone's implemented it yet.

You can get kind of close in Svelte Tweakpane UI be combining a Svelte reactive value with the `Slider` component's [`format`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/slider#format) prop to keep the slider's label in sync with the log value, something like this:

```svelte
<script lang="ts">
  import { Slider, Monitor, Separator } from 'svelte-tweakpane-ui';

  function logScale(x: number) {
    return Math.log10(1 + 99 * x) / Math.log10(100);
  }

  let linearValue = 1;
  $: logValue = logScale(linearValue);
</script>

<Slider
  bind:value={linearValue}
  min={0}
  max={1}
  format={(v) => logScale(v).toFixed(2)}
/>
```

Example: https://stackblitz.com/edit/vitejs-vite-x6nku5?file=src%2FApp.svelte

But the problem here is that `format` only affects the view of the display text input field, not the underlying value, so a number entered directly in the text field will be remapped from a linear to log scale.

You could work around this by using the [`Wheel`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/wheel) or [`Ring`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/ring) component, which are similar to sliders but have a [`wide`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/ring#wide) prop that lets you turn off the text input field, so there's nothing (visible) to keep in sync inside the Tweakpane control itself.

(This makes me think that a similar `wide` option for the `Slider` and `IntervalSlider` components might be nice...)

But again because of how the slider handle and text input field are coupled inside Tweakpane itself, there's not a great way to completely change the value scale that I can think of, sorry. Let me know if you end up finding an approach that works.

**Comment by ecstrema** [comment]
Thanks for the answer! Your solution perfectly fits my case, so I just modified it a bit and ended up with:

```svelte
<script lang="ts">
  let frequencyExponent = 6;

  $: frequency = Math.pow(10, frequencyExponent);
</script>

<Slider bind:value={frequencyExponent} label="Frequency" min={0} max={7} format={(value) => Math.pow(10, value).toExponential(1)}/>
```

And I'm using frequency elsewhere in the app. It works very well.
